# 라이브러리

In [1]:
# 파이썬 표준 라이브러리
import os

# 파이썬 서드파티 라이브러리
import pandas as pd

# 전역 변수 및 환경 설정

In [4]:
# 경로
current_dir = os.path.abspath('')
hankyung_path = current_dir + r'\datas\news_data\hankyung_data.json'
bloomingbit_path = current_dir + r'\datas\news_data\bloomingbit_data.json'
blockstreet_path = current_dir + r'\datas\news_data\blockstreet_data.json'

# Main

## hankyung

In [23]:
hankyung_df = pd.read_json(hankyung_path, orient='records', encoding='utf-8', dtype='string')

In [24]:
hankyung_df.head()

,news_title,news_first_upload_time,news_last_upload_time,news_author,news_content,news_url,news_category,news_website,note
0,비트코인 9.8만달러 재돌파…마이크로스트래티지 13% '급등',2025-01-04 08:47:00,2025-01-04 08:47:00,고정삼 기자,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2025010452817,암호화폐,hankyung,국내 사이트
1,"ai16z 설립자 '쇼우' 방한…""토큰 가치 높여 생태계 확장할 것""",2025-01-03 18:29:00,2025-01-03 18:29:00,이준형 기자,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/202501034932g,암호화폐,hankyung,국내 사이트
2,"""스스로 투자해요""…가상자산 시장 화두로 떠오른 'AI 에이전트' [황두현의 웹3+]",2025-01-03 14:22:00,2025-01-03 14:22:00,황두현 기자,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/202501022165g,암호화폐,hankyung,국내 사이트
3,'디지털 금' 떠오른 비트코인…'가상화폐 ETF' 경쟁,2025-01-03 12:31:00,2025-01-03 12:31:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2025010340115,암호화폐,hankyung,국내 사이트
4,새해 첫날 비트코인 소폭 상승…리플 11% 급등,2025-01-02 10:46:00,2025-01-02 10:46:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2025010213735,암호화폐,hankyung,국내 사이트

In [25]:
hankyung_df.tail()

,news_title,news_first_upload_time,news_last_upload_time,news_author,news_content,news_url,news_category,news_website,note
8772,"파죽지세 비트코인…미국에서 1만2000달러, 한국에선 1만4000달러 돌파",2017-12-06 15:43:00,2017-12-06 15:49:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2017120661036,암호화폐,hankyung,국내 사이트
8773,"비트코인 1만달러 넘었다…""제2의 튤립버블 vs 화폐개혁의 시작""",2017-11-29 07:38:00,2017-11-29 07:56:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2017112994686,암호화폐,hankyung,국내 사이트
8774,"[2018 투자 대전망]""가상화폐, 화폐 발전의 새 역사 쓸 것""",2017-11-15 18:11:00,2017-11-15 18:11:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2017111552556,암호화폐,hankyung,국내 사이트
8775,"올해 600% 급등한 비트코인…가상화폐, 제대로 투자하려면",2017-11-03 11:23:00,2017-11-03 13:47:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2017110334826,암호화폐,hankyung,국내 사이트
8776,"[특징주]SBI핀테크솔루션즈, 블록체인 사업 성장 기대 '강세'",2017-11-03 09:08:00,2017-11-03 09:46:00,<NA>,"<div class=""article-body"" id=""articletxt"" item...",https://www.hankyung.com/article/2017110328066,암호화폐,hankyung,국내 사이트

In [26]:
hankyung_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8777 entries, 0 to 8776
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   news_title              8777 non-null   string
 1   news_first_upload_time  8777 non-null   string
 2   news_last_upload_time   8777 non-null   string
 3   news_author             2472 non-null   string
 4   news_content            8777 non-null   string
 5   news_url                8777 non-null   string
 6   news_category           8777 non-null   string
 7   news_website            8777 non-null   string
 8   note                    8777 non-null   string
dtypes: string(9)
memory usage: 617.3 KB

## bloomingbit

In [27]:
bloomingbit_df = pd.read_json(bloomingbit_path, orient='records', encoding='utf-8', dtype='string')

In [28]:
bloomingbit_df.head()

,news_title,news_first_upload_time,news_last_upload_time,news_author,news_content,news_url,news_category,news_website,note
0,"작년은 밈코인의 해…""320%로 섹터 최고 수익률 기록""",2025-01-04 10:10:00,<NA>,황두현 기자,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/81107,전체 뉴스,bloomingbit,국내 사이트
1,[업비트]월렛 시스템 점검에 따른 에이다(ADA) 입출금 일시 중단 안내 (완료),2025-01-04 09:27:00,<NA>,거래소 공지봇 포모,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/81106,거래소 공지,bloomingbit,국내 사이트
2,비트코인 9.8만달러 재돌파…마이크로스트래티지 13% '급등',2025-01-04 09:00:00,<NA>,한경닷컴 뉴스룸,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/81105,PiCK,bloomingbit,국내 사이트
3,"""美, 비트코인 네트워크 해시레이트 40% 차지""",2025-01-04 08:58:00,<NA>,황두현 기자,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/81104,전체 뉴스,bloomingbit,국내 사이트
4,"반에크 CEO ""올해 비트코인 투자 늘려야""",2025-01-04 07:45:00,<NA>,황두현 기자,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/81103,전체 뉴스,bloomingbit,국내 사이트

In [29]:
bloomingbit_df.tail()

,news_title,news_first_upload_time,news_last_upload_time,news_author,news_content,news_url,news_category,news_website,note
79387,"빗썸코리아, 허백영 대표 재선임",2020-05-19 19:34:00,2020-05-28 23:55:00,블루밍비트 뉴스룸,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/6,전체 뉴스,bloomingbit,국내 사이트
79388,"코빗, SNS로 고객 소통채널 확대",2020-05-19 05:47:00,2020-05-28 23:56:00,블루밍비트 뉴스룸,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/5,전체 뉴스,bloomingbit,국내 사이트
79389,"업비트, 시장가‧예약 주문 기능 비트코인‧테더 시장까지 확대",2020-05-19 03:22:00,2020-05-28 23:37:00,블루밍비트 뉴스룸,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/4,전체 뉴스,bloomingbit,국내 사이트
79390,"블록크래프터스, 글로벌 액셀러레이팅 참가 기업 모집",2020-05-19 03:18:00,2020-05-28 23:56:00,블루밍비트 뉴스룸,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/3,전체 뉴스,bloomingbit,국내 사이트
79391,"해치랩스, 블록체인 솔루션 ‘헤네시스' 출시",2020-05-19 03:06:00,2020-05-28 23:56:00,블루밍비트 뉴스룸,"<div class=""_feedMainContent_feedDetailArticle...",https://bloomingbit.io/ko/feed/news/2,전체 뉴스,bloomingbit,국내 사이트

In [30]:
bloomingbit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79392 entries, 0 to 79391
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   news_title              79392 non-null  string
 1   news_first_upload_time  79392 non-null  string
 2   news_last_upload_time   33497 non-null  string
 3   news_author             79392 non-null  string
 4   news_content            79392 non-null  string
 5   news_url                79392 non-null  string
 6   news_category           79392 non-null  string
 7   news_website            79392 non-null  string
 8   note                    79392 non-null  string
dtypes: string(9)
memory usage: 5.5 MB

## blockstreet

In [31]:
blockstreet_df = pd.read_json(blockstreet_path, orient='records', encoding='utf-8', dtype='string')

In [32]:
blockstreet_df.head()

,news_title,news_first_upload_time,news_last_upload_time,news_author,news_content,news_url,news_category,news_website,note
0,"[코인 시황]비트코인, 트럼프 행정부 출범 기대감에 상승 유지",2025-01-03 16:33:00,2025-01-03 16:33:00,권승원 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
1,"머스크의 X, 암호화폐 결제 기능 출시 임박?…""美 위챗 나오나""",2025-01-03 12:39:00,2025-01-03 12:39:00,권승원 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
2,"갤럭시 디지털 ""BTC, 올해 18.5만달러 기록…금 시총, 20% 도달""",2025-01-03 10:18:00,2025-01-03 10:18:00,권승원 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
3,올해 美 솔라나 현물 ETF 시장 출시 두고 곳곳서 낙관론 상승,2025-01-03 10:07:00,2025-01-03 10:07:00,권승원 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
4,"모건 스탠리, 암호화폐 거래 서비스 제공 모색…""美 월가 대문 열리나""",2025-01-03 09:33:00,2025-01-03 09:33:00,권승원 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트

In [33]:
blockstreet_df.tail()

,news_title,news_first_upload_time,news_last_upload_time,news_author,news_content,news_url,news_category,news_website,note
5203,"[디지털화폐 전쟁③]美-유럽-日, 각국서 도입 논의 본격화",2021-03-10 08:20:00,2021-05-10 13:51:00,이어진 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
5204,"[디지털화폐 전쟁②]패권 장악하려는 중국, CBDC 도입 선봉장",2021-03-09 07:01:00,2021-05-10 13:51:00,이어진 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
5205,[디지털화폐 전쟁①]전 리브라로 불붙은 CBDC 전쟁…패권 경쟁으로 번져,2021-03-08 15:53:00,2021-05-10 13:51:00,주동일 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
5206,"페이팔, 디지털자산 사업부 별도 마련…“거래 수준 그치지 않을 것”",2021-03-08 07:05:00,2021-03-08 07:05:00,주동일 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트
5207,"페이팔, 디지털자산 커스터디 기업 커브 인수 시도",2021-03-03 16:58:00,2021-03-03 16:58:00,주동일 기자,"<div class=""view-body fs3""> <h3> <p> <sp...",https://www.blockstreet.co.kr/news/view?ud=202...,암호화폐,blockstreet,국내 사이트

In [34]:
blockstreet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5208 entries, 0 to 5207
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   news_title              5208 non-null   string
 1   news_first_upload_time  5208 non-null   string
 2   news_last_upload_time   5208 non-null   string
 3   news_author             5208 non-null   string
 4   news_content            5208 non-null   string
 5   news_url                5208 non-null   string
 6   news_category           5208 non-null   string
 7   news_website            5208 non-null   string
 8   note                    5208 non-null   string
dtypes: string(9)
memory usage: 366.3 KB